String? Pushups = "Push-ups are exercises to strengthen your arms and chest muscles. They are done by lying with your face towards the floor and pushing with your hands to raise your body until your arms are straight. Get on the floor on all fours, positioning your hands slightly wider than your shoulders. Don't lock out the elbows; keep them slightly bent. Extend your legs back so you are balanced on your hands and toes, your feet hip-width apart." ;
String? Benchpress = "The bench press, or chest press, is an upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.The barbell bench press is one of three lifts in the sport of powerlifting alongside the deadlift and squat, and is the only lift in the sport of Paralympic powerlifting. It is also used extensively in weight training, bodybuilding, and other types of training to develop the chest muscles. Bench press strength is important in combat sports as it tightly correlates to punching power. Bench press can also help contact athletes increase their performance because it can increase effective mass and functional hypertrophy of the upper body.";
String? Dumbbellpress = "Set up a bench at an incline of 30-45° and sit with your feet flat on the floor and your back on the bench. Lift the dumbbells to chest height with your palms facing forwards. Breathe out and push the dumbbells up until your arms are fully extended, using your pecs to power the movement. Don't let the dumbbells touch.";
String? Inclinedbenchpress = "Lie back and place your hands on the bar, slightly wider than shoulder-width apart, with your palms facing up. Lift the bar out of the rack and press it up until your arms are extended and your hands are above your shoulders. Slowly lower the bar to your chest, then press it back up again.";
String? Inclineddumbbellpress = "Sit on the bench and lean back. Hold a dumbbell in each hand, with hands positioned at your shoulders, elbows bent and angled down below your ribs. Relax your neck against the bench. Keep your feet flat on the floor. Brace your core and press both dumbbells straight up over your chest as you exhale.";
String? Declinedbenchpress = "In a decline bench press, the bench is set to 15 to 30 degrees on a decline. This angle places your upper body on a downward slope, which activates the lower pectoral muscles as you push weights away from your body. When part of a complete chest routine, decline bench presses can help your pecs look more defined. Using the decline bench to target your lower pecs is pretty much useless unless you're very lean and a competitive physique athlete,” says trainer Adam Wakefield. “You're better off getting strong on the flat bench and losing some body fat.";
String? Declineddumbbellpress= "Hold a dumbbell in each hand, shoulder-width apart and overhand grip. Lie back on a decline bench and extend your arms straight above you. Lower the weights slowly until they reach your chest, then push the dumbbells back to starting position. More From Fitness.";
String? Machinefly = "A machine fly, alternatively called a seated lever fly or 'Pec Deck' fly is a strength training exercise based on the free weight chest fly. As with the chest fly, the hand and arm move through an arc while the elbow is kept at a constant angle. The fly machine is ideal for increasing chest strength and muscle mass by targeting the pectoralis muscles. You have two sets of pectoral muscles on each side of the front of your chest: the pectoralis major and the pectoralis minor.";
String? Cablecrossover = "A crossover cable is a type of cable installation that is used for the interconnection of two similar devices. It is enabled by reversing the transmission and receiving pins at both ends, so that output from one computer becomes input to the other, and vice versa. Stand in the centre of the machine with feet shoulder-width apart. Bend your torso forwards slightly, keeping your spine neutral and back straight, and bend your elbows slightly as well, with your wrists facing the floor. Keeping your core engaged, pull both handles down and across your body.";
String? Cablepushdown = "Stand with your feet hip-width apart, or place one in front of the other if it helps you balance. Pull the cable down until the bar touches your thighs and pause to squeeze your triceps at the bottom of the move. Then slowly raise the bar back to the starting position. A tricep pushdown is a simple exercise that uses resistance (usually from a cable machine) to work all three heads of the tricep brachii through extension of the elbow joint.";
String? Overheadextention = "An overhead tricep extension, also known as a dumbbell tricep extension, is an isolation exercise that targets your triceps muscles. Perform overhead tricep extensions by holding a pair of dumbbells and standing with your feet shoulder-width apart. Raise the dumbbells over your head. The overhead rope extension exercise works all three heads of the triceps brachii muscle due to its elbow extension component.";
String? Dipsonbench = "Walk your feet out and extend your legs, lifting your bottom off the bench and holding there with extended arms. Hinging at the elbow, lower your body down as far as you can go, or until your arms form a 90-degree angle. Push up through your palms back to start.";
String? Closegripbarbellbenchpress= "The close grip bench press is a compound exercise performed by lying on a flat bench and lifting a weighted barbell. This type of bench press uses a closer grip than a traditional bench press. The posture of a close grip bench press puts special emphasis on the triceps. Lie flat on the bench using a close grip (about shoulder width). Lift the bar with assistance from the rack, arms locked, and holding bar straight over you. Inhale and slowly bring the bar down toward your chest keeping elbows close to your body for the entire exercise.";
String? Diamondpushups= "Diamond push-ups, also known as triangle push-ups, are a more advanced variation of the classic push-up. Practice diamond push-ups by bringing your hands close together to form a diamond or triangle shape below your chest. Keep your back and legs in a straight line and push yourself off the ground.";
String? Kickback= "A kickback, also known as a glute kickback, is a bodyweight exercise that targets muscle groups throughout your lower body—specifically your glute muscles. Perform kickbacks by getting on all fours or in a kneeling push-up position. Keep your back straight and your core engaged as you lift one leg up behind you.";
String? Singlearmextention= "Hold a dumbbell in one hand directly behind your head, with your elbow bent and pointed towards the ceiling. Extend through your elbow until your arm is straight and the dumbbell is directly above you. Lower your arm back to starting position and repeat.";
String? Skullcrusher= "The skull crusher is a push exercise that isolates the triceps brachii, working it from the elbow all the way up to the latissimus dorsi muscle of the back. 2 The triceps brachii contains three heads. which can be targeted by doing a variety of lying triceps extension variations.";
String? Chinups= "The chin-up (also known as a chin or chinup) is a strength training exercise. People frequently do this exercise with the intention of strengthening muscles such as the latissimus dorsi and biceps, which extend the shoulder and flex the elbow, respectively. In this maneuver, the palms are faced towards the body.";
String? Latpulldown= "What Is a Lat Pulldown? A lat pulldown is a compound exercise that targets your back muscles. Perform the lat pulldown exercise by sitting in front of a cable machine with a pulldown bar. Grab the bar and bend your elbows to lower it closer towards your upper chest. The lat pulldown works many muscles, including the latissimus dorsi, pectoralis major, rotator cuff, and biceps brachii.";
String? Latpulldownwidegrip= "Begin by grabbing the bar with your palms facing away from you and your hands wider than shoulder width apart. Keeping your lower body still, squeeze your lats to pull yourself upwards until your chin passes the bar. Slowly return to the starting position. Repeat!";
String? Bentover= "Step 1: Hold onto a barbell with your palms facing down....\nStep 2: While keeping your torso stationary, lift the barbell toward you....\nStep 3: Slowly lower the barbell back to the starting position.\nStep 4: Repeat the process for the number of repetitions in your workout routine.\nImage result for bent over descriptionThe bent over row primarily works the latissimus dorsi (the large wing-like muscles in your back), the middle and lower trapezius, the rhomboids, and the posterior deltoids. These are the prime movers that are responsible for the movement in the exercise.";
String? Latpulldownvgrip= "Grip the v-bar and extend your arms up over you r head. Push your chest up and pull your shoulders back. Pull the v-bar down to chin level (90 degrees) as you push your chest up to the bar. Squeeze your shoulder blades together and keep your shoulders down.\nImage result for lat pull down v grip descriptionV-Bar Pull Down OverviewThe V-bar lat pull down is a variation of the lat pull down and an exercise commonly used to target the muscles of the back. Commonly mistaken for a close grip pull down, the V-bar pull down does utilize a closer grip than the traditional lat pull down.";
String? Latpulldownreversegrip= "Image result for lat pull down reverse descriptionGrasp the bar with a wide grip, looking forward with your torso upright. Retract your shoulder blades and pull the bar down in front of you to your upper chest. Squeeze your lats at the bottom of the move. Resist the temptation to lean back to aid the movement.";
String? Rowingdumbbell= "The single-arm dumbbell row is one of those exercises that won't go out of style. It's simple as heck to do — you literally kneel on a bench and row your arm to your side — and it requires just a dumbbell to load the movement. It's also a unilateral exercise, meaning it trains one side of your body at a time";
String? Rowingclosegrip= "The close grip cable row primarily targets the Latissimus Doris (Back/Lats) muscle group. You will also use your rear delt (back of the shoulder) when you pull from the front to the back (shoulder extension). Your biceps (front of your arm) and forearm also assist in this exercise.";
String? Barbellcurl= "A barbell curl is a variation of the biceps curl that uses a weighted barbell. Perform barbell curls by grabbing a barbell with a shoulder-width supinated grip (palms facing towards your body). Hinge your elbows, and lift the barbell toward your chest. Hold the barbell with both hands facing up so the wrists, elbows, and shoulders are in a straight line about shoulder-width apart. Lift the barbell toward the shoulders while bending the elbows and keeping them next to the middle of the body. Slowly lower the weight to return to the starting position.";
String? Dumbbellcurl= "Bending at the elbow, lift one dumbbell toward your shoulder, rotating your arm as it moves up so that the palm with the dumbbell faces up during the movement and eventually faces the shoulder. Lower the weight to the starting position and perform the same movement with the other arm.";
String? Inclineddumbbellcurl= "Perform incline dumbbell curls by sitting on an incline bench set to a 45- or 60-degree angle. Hold a pair of dumbbells at your side. Squeeze your biceps and bend your elbows to lift the dumbbells to shoulder level, then lower them again. Repeat this movement for the desired number of reps.";
String? Ezpreachercurl= "Position your upper arms and chest against the preacher bench pad while holding the E-Z Curl Bar at shoulder length. As you exhale, use the biceps to curl the weight up until your biceps are fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second.";
String? Closegrip= "The close-grip barbell curl is a curl variation where the hands are closer than shoulder width. It is thought that this helps build the outer biceps head and the peak. This curl variation is usually performed for moderate to high reps, such as 8-12 reps per set.";
String? Singlearmpreachercurl= "Curl the dumbbell in towards your chin and upper chest in a single smooth arc. Hold for a count of one while squeezing your biceps. Lower the dumbbell by extending your arms back to the starting position. Repeat for the desired number of repetitions then change to your other arm.";
String? Concentrationcurl= "Slowly curl the weight up, only moving your forearms, the position of your upper arm on your thigh will help you keep it still during the exercise. At the top of the move, pause for a beat and squeeze your biceps, then slowly lower the weight back to the start. Do all your reps on one arm, then switch to the other.";
String? Hammercurl= "The hammer curl, also known as the dumbbell hammer curl or the neutral grip dumbbell curl, is a strength training exercise that targets your biceps and forearms. The hammer curl varies from the traditional bicep curl by using a neutral grip with your palms facing each other during the full range of motion.";
String? Barbellseatedrow= "Sit on the bench holding a barbell in front of your shoulders with an overhand grip. Press the weight up above your head until your arms are fully extended. Return slowly to the start position.";
String? Shoulderdumbbellpress= "Sit on an upright bench holding a dumbbell in each hand at shoulder height with your palms facing away from you. Keep your chest up and your core braced, and look straight forward throughout the move. Press the weights directly upwards until your arms are straight and the weights touch above your head.";
String? Arnolddumbbellpress= "Hold a dumbbell in each hand with your arm bent, as in the top of a biceps curl, so your palms are facing you. Now, instead of pushing straight up, spread your arms to each side laterally, then press your arms up and twist your hands so your palms face forwards.";
String? Dumbbellfrontraises= "Stand with your feet about shoulder-width apart. Let your arms hang in front of you with the dumbbells in front of the thighs (palms facing the thighs). Your back is straight, your feet are planted flat on the floor, and your abdominal muscles are engaged. Lift the weights upward while inhaling.";
String? Lateralraises= "A lateral raise is a strength training shoulder exercise characterized by lifting a pair of dumbbells away from your body in an external rotation. Lateral raises work the trapezius muscle in your upper back as well as the deltoid muscle group in your shoulders—particularly the anterior and lateral deltoids.";
String? Barbellupright= "Hold a barbell in front of your body with your palms facing you and bend your knees slightly. Keep your back straight, head up and torso stationary as you lift the barbell towards your chin. Raise your elbows up and to the sides using your shoulder muscles to lift the weight.";
String? Machinereversefly= "Reach forward and grasp each handle with a pronated or neutral grip. Contract the rear delts while keeping the elbows bent and open the arms in a reverse fly motion. Slowly lower the handles back to the starting position and repeat for the desired number of repetitions.";
String? Barbellsquats=  "What Is a Barbell Squat? A barbell squat, also known as a barbell back squat, is a compound exercise that activates muscle groups throughout your lower body, including your hamstrings, glutes, and lower back muscles. Perform barbell squats by standing with your feet shoulder-width apart.";
String? Legextention= "The leg extension, or knee extension, is a type of strength training exercise. It's an excellent move for strengthening your quadriceps, which are in the front of your upper legs. Leg extensions are done on a leg extension machine. You sit on the machine with a weighted pad on top of your lower legs.\n1. Raise the padded bar by extending your quads to straighten your legs.\n2. Once your legs are extended, hold this position for one second whilst squeezing your quads.\n3. Slowly lower the padded bar back down towards the starting position without letting the weight stop.\n4. Repeat!";
String? Lyinglegcurl= "Lie face down on the leg curl machine with the pad resting just under your calves. Grab the side handles and keep your body flat to the bench as you curl your legs up as far as possible. Lower and repeat. More From Fitness.\n1. Exhale and flex your knees, pulling your ankles as close to your buttocks as you can. Keep your hips firmly on the bench.\n2. Hold briefly.\n3. Inhale as you return your feet to the starting position in a slow and controlled movement.";
String? Smithmachinesquats= "How to Smith machine squat: Stand in a Smith machine with a shoulder-width stance and the bar across your shoulders and traps. With your chest high, keep your head forward and maintain the arch in your back. Bend at the knees and hips as if you're sitting back in a chair until your thighs are parallel to the floor.";
String? Hacksquats= " The HS is a Squat variation that is performed on a machine and involves pushing the weight away from you, at an angle, as you stand back up. You must stand on the plate with your body leaning back against the pads. The weight is moved during the concentric phase of the movement. Step into the machine, placing your feet shoulder-width apart and your shoulders and back against the pads. Release the safety handles, inhale, and lower down, bending your knees until they reach a 90-degree angle. Pause here, then push up through the back of your feet to extend your legs back to the starting position.";
String? Legpress= "The leg press, a type of resistance training exercise, is an excellent way to strengthen your legs. It's done by pushing your legs against weights on a leg press machine. Like all strength training exercises, leg presses build muscle, reduce the risk of injury, and counteract age-related muscle loss. Pause for a second at the bottom position. To begin the upward movement, push your feet into the resistance plate. Place emphasis on pushing through your midfoot and heels while keeping your toes engaged. At the end of each repetition, your legs should be outstretched with a slight bend in your knees.";
String? Steppinglunges= "Stand on a step or a box and place hands on hips. Step back with left leg, lowering your body into a lunge. Push through right foot and straighten right leg as you return to standing position. Repeat on the other side.";
String? Jogging= "Jogging is a form of trotting or running at a slow or leisurely pace. The main intention is to increase physical fitness with less stress on ...\nRegularly jogging can help you lose weight, especially if you also modify your diet. Jogging can also help you improve your heart health and immune system, reduce insulin resistance, cope with stress and depression, and maintain flexibility as you age.";
String? Jumpingrope= "Jumping rope is a form of exercise that involves swinging a rope around your body and jumping over it as it passes under your feet. It's a form of cardiovascular training since the constant movement elevates your heart rate. The basic concept of jumping rope is simple. The activity, game or exercise in which a person must jump, bounce or skip repeatedly while a length of rope is swung over and under, both ends held in the hands of the jumper, or alternately, held by two other participants.";
String? Cycling= "cycling, use of a bicycle for sport, recreation, or transportation. The sport of cycling consists of professional and amateur races, which are held mostly in continental Europe, the United States, and Asia. The recreational use of the bicycle is widespread in Europe and the United States. Cycling improves strength, balance and coordination. It may also help to prevent falls and fractures. Riding a bike is an ideal form of exercise if you have osteoarthritis, because it is a low-impact exercise that places little stress on joints.";
String? Swimming= "swimming, in recreation and sports, the propulsion of the body through water by combined arm and leg motions and the natural flotation of the body. Swimming is a great workout because you need to move your whole body against the resistance of the water. Swimming is a good all-round activity because it: keeps your heart rate up but takes some of the impact stress off your body. builds endurance, muscle strength and cardiovascular fitness.";
String? Sprinting= "Sprint training is an exercise regimen that burns fat, builds muscle, and boosts BMR (Basal Metabolic Rate). Because studies have shown that short bursts of running are more efficient than long walks or jogs, sprint training is becoming the recommended method of choice for cardiovascular exercise.";
String? Stretch= "Stretching is a form of physical exercise in which a specific muscle or tendon (or muscle group) is deliberately flexed or stretched in order to improve the muscle's felt elasticity and achieve comfortable muscle tone. The result is a feeling of increased muscle control, flexibility, and range of motion. Stretching keeps the muscles flexible, strong, and healthy, and we need that flexibility to maintain a range of motion in the joints. Without it, the muscles shorten and become tight. Then, when you call on the muscles for activity, they are weak and unable to extend all the way."; 
String? Conventionaldeadlift= "A conventional deadlift is when the lifter keeps their feet about shoulder-width apart and lifts with their hands outside their knees.\n\nThe ideal deadlift stance for a conventional (i.e. not sumo) deadlift is for the feet to be around hip-width apart, and the feet slightly turned out. Another way to find the ideal stance is to do a couple of vertical jumps as high as you can; where your feet land is where your stance should be for deadlifting.";
String? Squats= "Begin by squatting down as if you're sitting into a chair. Your ankles, knees, and hips will bend in unison while your spine stays straight. As you begin to lower, your knees will travel forward over your toes, and your hips will travel backward to keep your center of gravity over your feet. Most fitness experts and strength coaches will agree that being able to perform at least 20-50 consecutive bodyweight squats with good form is a good basic standard to go by.";
String? Barbellbenchpress= "Grip a barbell with hands slightly wider than shoulder width. The bar should be directly over the shoulders. Press your feet firmly into the ground and keep your hips on the bench throughout the entire movement. Keep your core engaged and maintain a neutral spine position throughout the movement. For a 198-pound man — a very close match for the national average — who has no experience benching whatsoever, ExRx.net places the standard at 135 pounds. That jumps up to 175 for a novice and 215 for an intermediate lifter. At the advanced level, the number is 290 pounds.";
String? Sumodeadlift= "The Sumo deadlift is a variation of the conventional deadlift often adopted by powerlifters. The difference between the two lies in the setup of the lifter's feet and hands. When the bar is gripped with the lifter's hands inside their legs, the form is considered 'Sumo'.\n\nLike other deadlift variations, the sumo deadlift works the glutes, hamstrings, and back.\n\nThe main difference between the sumo and the conventional deadlift is the position of the feet and hands. Instead of being about hip-width apart, with sumo the feet are positioned wider than your hands. How wide apart they are depends on your height, but they will be much farther apart than shoulder width";
String? Yoga= "Yoga is essentially a spiritual discipline based on an extremely subtle science, which focuses on bringing harmony between mind and body. It is an art and scince of healthy living. The word 'Yoga' is derived from the Sanskrit root 'Yuj', meaning 'to join' or 'to yoke' or 'to unite'.\n\nYoga improves strength, balance and flexibility. Slow movements and deep breathing increase blood flow and warm up muscles, while holding a pose can build strength.";







String? Eggs = "egg, the content of the hard-shelled reproductive body produced by a bird, considered as food. While the primary role of the egg obviously is to reproduce the species, most eggs laid by domestic fowl, except those specifically set aside for hatching, are not fertilized but are sold mainly for human consumption. Eggs produced in quantity come from chickens, ducks, geese, turkeys, guinea fowl, pigeons, pheasants, and quail. This article describes the processing of chicken eggs, which represent the bulk of egg production in the United States and Europe. Duck eggs are consumed as food in parts of Europe and Asia, and goose eggs are also a food in many European countries. Commercial production of turkey and pigeon eggs is almost entirely confined to those used for producing turkey poults and young pigeons (squabs). Pheasant and quail eggs provide birds for hobby or sport use.";