// EXERCISES DESCRIPTION -


String? Pushups = "Push-ups are exercises to strengthen your arms and chest muscles. They are done by lying with your face towards the floor and pushing with your hands to raise your body until your arms are straight. Get on the floor on all fours, positioning your hands slightly wider than your shoulders. Don't lock out the elbows; keep them slightly bent. Extend your legs back so you are balanced on your hands and toes, your feet hip-width apart." ;
String? Benchpress = "The bench press, or chest press, is an upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench. The exercise uses the pectoralis major, the anterior deltoids, and the triceps, among other stabilizing muscles. A barbell is generally used to hold the weight, but a pair of dumbbells can also be used.The barbell bench press is one of three lifts in the sport of powerlifting alongside the deadlift and squat, and is the only lift in the sport of Paralympic powerlifting. It is also used extensively in weight training, bodybuilding, and other types of training to develop the chest muscles. Bench press strength is important in combat sports as it tightly correlates to punching power. Bench press can also help contact athletes increase their performance because it can increase effective mass and functional hypertrophy of the upper body.";
String? Dumbbellpress = "Set up a bench at an incline of 30-45° and sit with your feet flat on the floor and your back on the bench. Lift the dumbbells to chest height with your palms facing forwards. Breathe out and push the dumbbells up until your arms are fully extended, using your pecs to power the movement. Don't let the dumbbells touch.";
String? Inclinedbenchpress = "Lie back and place your hands on the bar, slightly wider than shoulder-width apart, with your palms facing up. Lift the bar out of the rack and press it up until your arms are extended and your hands are above your shoulders. Slowly lower the bar to your chest, then press it back up again.";
String? Inclineddumbbellpress = "Sit on the bench and lean back. Hold a dumbbell in each hand, with hands positioned at your shoulders, elbows bent and angled down below your ribs. Relax your neck against the bench. Keep your feet flat on the floor. Brace your core and press both dumbbells straight up over your chest as you exhale.";
String? Declinedbenchpress = "In a decline bench press, the bench is set to 15 to 30 degrees on a decline. This angle places your upper body on a downward slope, which activates the lower pectoral muscles as you push weights away from your body. When part of a complete chest routine, decline bench presses can help your pecs look more defined. Using the decline bench to target your lower pecs is pretty much useless unless you're very lean and a competitive physique athlete,” says trainer Adam Wakefield. “You're better off getting strong on the flat bench and losing some body fat.";
String? Declineddumbbellpress= "Hold a dumbbell in each hand, shoulder-width apart and overhand grip. Lie back on a decline bench and extend your arms straight above you. Lower the weights slowly until they reach your chest, then push the dumbbells back to starting position. More From Fitness.";
String? Machinefly = "A machine fly, alternatively called a seated lever fly or 'Pec Deck' fly is a strength training exercise based on the free weight chest fly. As with the chest fly, the hand and arm move through an arc while the elbow is kept at a constant angle. The fly machine is ideal for increasing chest strength and muscle mass by targeting the pectoralis muscles. You have two sets of pectoral muscles on each side of the front of your chest: the pectoralis major and the pectoralis minor.";
String? Cablecrossover = "A crossover cable is a type of cable installation that is used for the interconnection of two similar devices. It is enabled by reversing the transmission and receiving pins at both ends, so that output from one computer becomes input to the other, and vice versa. Stand in the centre of the machine with feet shoulder-width apart. Bend your torso forwards slightly, keeping your spine neutral and back straight, and bend your elbows slightly as well, with your wrists facing the floor. Keeping your core engaged, pull both handles down and across your body.";
String? Cablepushdown = "Stand with your feet hip-width apart, or place one in front of the other if it helps you balance. Pull the cable down until the bar touches your thighs and pause to squeeze your triceps at the bottom of the move. Then slowly raise the bar back to the starting position. A tricep pushdown is a simple exercise that uses resistance (usually from a cable machine) to work all three heads of the tricep brachii through extension of the elbow joint.";
String? Overheadextention = "An overhead tricep extension, also known as a dumbbell tricep extension, is an isolation exercise that targets your triceps muscles. Perform overhead tricep extensions by holding a pair of dumbbells and standing with your feet shoulder-width apart. Raise the dumbbells over your head. The overhead rope extension exercise works all three heads of the triceps brachii muscle due to its elbow extension component.";
String? Dipsonbench = "Walk your feet out and extend your legs, lifting your bottom off the bench and holding there with extended arms. Hinging at the elbow, lower your body down as far as you can go, or until your arms form a 90-degree angle. Push up through your palms back to start.";
String? Closegripbarbellbenchpress= "The close grip bench press is a compound exercise performed by lying on a flat bench and lifting a weighted barbell. This type of bench press uses a closer grip than a traditional bench press. The posture of a close grip bench press puts special emphasis on the triceps. Lie flat on the bench using a close grip (about shoulder width). Lift the bar with assistance from the rack, arms locked, and holding bar straight over you. Inhale and slowly bring the bar down toward your chest keeping elbows close to your body for the entire exercise.";
String? Diamondpushups= "Diamond push-ups, also known as triangle push-ups, are a more advanced variation of the classic push-up. Practice diamond push-ups by bringing your hands close together to form a diamond or triangle shape below your chest. Keep your back and legs in a straight line and push yourself off the ground.";
String? Kickback= "A kickback, also known as a glute kickback, is a bodyweight exercise that targets muscle groups throughout your lower body—specifically your glute muscles. Perform kickbacks by getting on all fours or in a kneeling push-up position. Keep your back straight and your core engaged as you lift one leg up behind you.";
String? Singlearmextention= "Hold a dumbbell in one hand directly behind your head, with your elbow bent and pointed towards the ceiling. Extend through your elbow until your arm is straight and the dumbbell is directly above you. Lower your arm back to starting position and repeat.";
String? Skullcrusher= "The skull crusher is a push exercise that isolates the triceps brachii, working it from the elbow all the way up to the latissimus dorsi muscle of the back. 2 The triceps brachii contains three heads. which can be targeted by doing a variety of lying triceps extension variations.";
String? Chinups= "The chin-up (also known as a chin or chinup) is a strength training exercise. People frequently do this exercise with the intention of strengthening muscles such as the latissimus dorsi and biceps, which extend the shoulder and flex the elbow, respectively. In this maneuver, the palms are faced towards the body.";
String? Latpulldown= "What Is a Lat Pulldown? A lat pulldown is a compound exercise that targets your back muscles. Perform the lat pulldown exercise by sitting in front of a cable machine with a pulldown bar. Grab the bar and bend your elbows to lower it closer towards your upper chest. The lat pulldown works many muscles, including the latissimus dorsi, pectoralis major, rotator cuff, and biceps brachii.";
String? Latpulldownwidegrip= "Begin by grabbing the bar with your palms facing away from you and your hands wider than shoulder width apart. Keeping your lower body still, squeeze your lats to pull yourself upwards until your chin passes the bar. Slowly return to the starting position. Repeat!";
String? Bentover= "Step 1: Hold onto a barbell with your palms facing down....\nStep 2: While keeping your torso stationary, lift the barbell toward you....\nStep 3: Slowly lower the barbell back to the starting position.\nStep 4: Repeat the process for the number of repetitions in your workout routine.\nImage result for bent over descriptionThe bent over row primarily works the latissimus dorsi (the large wing-like muscles in your back), the middle and lower trapezius, the rhomboids, and the posterior deltoids. These are the prime movers that are responsible for the movement in the exercise.";
String? Latpulldownvgrip= "Grip the v-bar and extend your arms up over you r head. Push your chest up and pull your shoulders back. Pull the v-bar down to chin level (90 degrees) as you push your chest up to the bar. Squeeze your shoulder blades together and keep your shoulders down.\nImage result for lat pull down v grip descriptionV-Bar Pull Down OverviewThe V-bar lat pull down is a variation of the lat pull down and an exercise commonly used to target the muscles of the back. Commonly mistaken for a close grip pull down, the V-bar pull down does utilize a closer grip than the traditional lat pull down.";
String? Latpulldownreversegrip= "Image result for lat pull down reverse descriptionGrasp the bar with a wide grip, looking forward with your torso upright. Retract your shoulder blades and pull the bar down in front of you to your upper chest. Squeeze your lats at the bottom of the move. Resist the temptation to lean back to aid the movement.";
String? Rowingdumbbell= "The single-arm dumbbell row is one of those exercises that won't go out of style. It's simple as heck to do — you literally kneel on a bench and row your arm to your side — and it requires just a dumbbell to load the movement. It's also a unilateral exercise, meaning it trains one side of your body at a time";
String? Rowingclosegrip= "The close grip cable row primarily targets the Latissimus Doris (Back/Lats) muscle group. You will also use your rear delt (back of the shoulder) when you pull from the front to the back (shoulder extension). Your biceps (front of your arm) and forearm also assist in this exercise.";
String? Barbellcurl= "A barbell curl is a variation of the biceps curl that uses a weighted barbell. Perform barbell curls by grabbing a barbell with a shoulder-width supinated grip (palms facing towards your body). Hinge your elbows, and lift the barbell toward your chest. Hold the barbell with both hands facing up so the wrists, elbows, and shoulders are in a straight line about shoulder-width apart. Lift the barbell toward the shoulders while bending the elbows and keeping them next to the middle of the body. Slowly lower the weight to return to the starting position.";
String? Dumbbellcurl= "Bending at the elbow, lift one dumbbell toward your shoulder, rotating your arm as it moves up so that the palm with the dumbbell faces up during the movement and eventually faces the shoulder. Lower the weight to the starting position and perform the same movement with the other arm.";
String? Inclineddumbbellcurl= "Perform incline dumbbell curls by sitting on an incline bench set to a 45- or 60-degree angle. Hold a pair of dumbbells at your side. Squeeze your biceps and bend your elbows to lift the dumbbells to shoulder level, then lower them again. Repeat this movement for the desired number of reps.";
String? Ezpreachercurl= "Position your upper arms and chest against the preacher bench pad while holding the E-Z Curl Bar at shoulder length. As you exhale, use the biceps to curl the weight up until your biceps are fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second.";
String? Closegrip= "The close-grip barbell curl is a curl variation where the hands are closer than shoulder width. It is thought that this helps build the outer biceps head and the peak. This curl variation is usually performed for moderate to high reps, such as 8-12 reps per set.";
String? Singlearmpreachercurl= "Curl the dumbbell in towards your chin and upper chest in a single smooth arc. Hold for a count of one while squeezing your biceps. Lower the dumbbell by extending your arms back to the starting position. Repeat for the desired number of repetitions then change to your other arm.";
String? Concentrationcurl= "Slowly curl the weight up, only moving your forearms, the position of your upper arm on your thigh will help you keep it still during the exercise. At the top of the move, pause for a beat and squeeze your biceps, then slowly lower the weight back to the start. Do all your reps on one arm, then switch to the other.";
String? Hammercurl= "The hammer curl, also known as the dumbbell hammer curl or the neutral grip dumbbell curl, is a strength training exercise that targets your biceps and forearms. The hammer curl varies from the traditional bicep curl by using a neutral grip with your palms facing each other during the full range of motion.";
String? Barbellseatedrow= "Sit on the bench holding a barbell in front of your shoulders with an overhand grip. Press the weight up above your head until your arms are fully extended. Return slowly to the start position.";
String? Shoulderdumbbellpress= "Sit on an upright bench holding a dumbbell in each hand at shoulder height with your palms facing away from you. Keep your chest up and your core braced, and look straight forward throughout the move. Press the weights directly upwards until your arms are straight and the weights touch above your head.";
String? Arnolddumbbellpress= "Hold a dumbbell in each hand with your arm bent, as in the top of a biceps curl, so your palms are facing you. Now, instead of pushing straight up, spread your arms to each side laterally, then press your arms up and twist your hands so your palms face forwards.";
String? Dumbbellfrontraises= "Stand with your feet about shoulder-width apart. Let your arms hang in front of you with the dumbbells in front of the thighs (palms facing the thighs). Your back is straight, your feet are planted flat on the floor, and your abdominal muscles are engaged. Lift the weights upward while inhaling.";
String? Lateralraises= "A lateral raise is a strength training shoulder exercise characterized by lifting a pair of dumbbells away from your body in an external rotation. Lateral raises work the trapezius muscle in your upper back as well as the deltoid muscle group in your shoulders—particularly the anterior and lateral deltoids.";
String? Barbellupright= "Hold a barbell in front of your body with your palms facing you and bend your knees slightly. Keep your back straight, head up and torso stationary as you lift the barbell towards your chin. Raise your elbows up and to the sides using your shoulder muscles to lift the weight.";
String? Machinereversefly= "Reach forward and grasp each handle with a pronated or neutral grip. Contract the rear delts while keeping the elbows bent and open the arms in a reverse fly motion. Slowly lower the handles back to the starting position and repeat for the desired number of repetitions.";
String? Barbellsquats=  "What Is a Barbell Squat? A barbell squat, also known as a barbell back squat, is a compound exercise that activates muscle groups throughout your lower body, including your hamstrings, glutes, and lower back muscles. Perform barbell squats by standing with your feet shoulder-width apart.";
String? Legextention= "The leg extension, or knee extension, is a type of strength training exercise. It's an excellent move for strengthening your quadriceps, which are in the front of your upper legs. Leg extensions are done on a leg extension machine. You sit on the machine with a weighted pad on top of your lower legs.\n1. Raise the padded bar by extending your quads to straighten your legs.\n2. Once your legs are extended, hold this position for one second whilst squeezing your quads.\n3. Slowly lower the padded bar back down towards the starting position without letting the weight stop.\n4. Repeat!";
String? Lyinglegcurl= "Lie face down on the leg curl machine with the pad resting just under your calves. Grab the side handles and keep your body flat to the bench as you curl your legs up as far as possible. Lower and repeat. More From Fitness.\n1. Exhale and flex your knees, pulling your ankles as close to your buttocks as you can. Keep your hips firmly on the bench.\n2. Hold briefly.\n3. Inhale as you return your feet to the starting position in a slow and controlled movement.";
String? Smithmachinesquats= "How to Smith machine squat: Stand in a Smith machine with a shoulder-width stance and the bar across your shoulders and traps. With your chest high, keep your head forward and maintain the arch in your back. Bend at the knees and hips as if you're sitting back in a chair until your thighs are parallel to the floor.";
String? Hacksquats= " The HS is a Squat variation that is performed on a machine and involves pushing the weight away from you, at an angle, as you stand back up. You must stand on the plate with your body leaning back against the pads. The weight is moved during the concentric phase of the movement. Step into the machine, placing your feet shoulder-width apart and your shoulders and back against the pads. Release the safety handles, inhale, and lower down, bending your knees until they reach a 90-degree angle. Pause here, then push up through the back of your feet to extend your legs back to the starting position.";
String? Legpress= "The leg press, a type of resistance training exercise, is an excellent way to strengthen your legs. It's done by pushing your legs against weights on a leg press machine. Like all strength training exercises, leg presses build muscle, reduce the risk of injury, and counteract age-related muscle loss. Pause for a second at the bottom position. To begin the upward movement, push your feet into the resistance plate. Place emphasis on pushing through your midfoot and heels while keeping your toes engaged. At the end of each repetition, your legs should be outstretched with a slight bend in your knees.";
String? Steppinglunges= "Stand on a step or a box and place hands on hips. Step back with left leg, lowering your body into a lunge. Push through right foot and straighten right leg as you return to standing position. Repeat on the other side.";
String? Jogging= "Jogging is a form of trotting or running at a slow or leisurely pace. The main intention is to increase physical fitness with less stress on ...\nRegularly jogging can help you lose weight, especially if you also modify your diet. Jogging can also help you improve your heart health and immune system, reduce insulin resistance, cope with stress and depression, and maintain flexibility as you age.";
String? Jumpingrope= "Jumping rope is a form of exercise that involves swinging a rope around your body and jumping over it as it passes under your feet. It's a form of cardiovascular training since the constant movement elevates your heart rate. The basic concept of jumping rope is simple. The activity, game or exercise in which a person must jump, bounce or skip repeatedly while a length of rope is swung over and under, both ends held in the hands of the jumper, or alternately, held by two other participants.";
String? Cycling= "cycling, use of a bicycle for sport, recreation, or transportation. The sport of cycling consists of professional and amateur races, which are held mostly in continental Europe, the United States, and Asia. The recreational use of the bicycle is widespread in Europe and the United States. Cycling improves strength, balance and coordination. It may also help to prevent falls and fractures. Riding a bike is an ideal form of exercise if you have osteoarthritis, because it is a low-impact exercise that places little stress on joints.";
String? Swimming= "swimming, in recreation and sports, the propulsion of the body through water by combined arm and leg motions and the natural flotation of the body. Swimming is a great workout because you need to move your whole body against the resistance of the water. Swimming is a good all-round activity because it: keeps your heart rate up but takes some of the impact stress off your body. builds endurance, muscle strength and cardiovascular fitness.";
String? Sprinting= "Sprint training is an exercise regimen that burns fat, builds muscle, and boosts BMR (Basal Metabolic Rate). Because studies have shown that short bursts of running are more efficient than long walks or jogs, sprint training is becoming the recommended method of choice for cardiovascular exercise.";
String? Stretch= "Stretching is a form of physical exercise in which a specific muscle or tendon (or muscle group) is deliberately flexed or stretched in order to improve the muscle's felt elasticity and achieve comfortable muscle tone. The result is a feeling of increased muscle control, flexibility, and range of motion. Stretching keeps the muscles flexible, strong, and healthy, and we need that flexibility to maintain a range of motion in the joints. Without it, the muscles shorten and become tight. Then, when you call on the muscles for activity, they are weak and unable to extend all the way."; 
String? Conventionaldeadlift= "A conventional deadlift is when the lifter keeps their feet about shoulder-width apart and lifts with their hands outside their knees.\n\nThe ideal deadlift stance for a conventional (i.e. not sumo) deadlift is for the feet to be around hip-width apart, and the feet slightly turned out. Another way to find the ideal stance is to do a couple of vertical jumps as high as you can; where your feet land is where your stance should be for deadlifting.";
String? Squats= "Begin by squatting down as if you're sitting into a chair. Your ankles, knees, and hips will bend in unison while your spine stays straight. As you begin to lower, your knees will travel forward over your toes, and your hips will travel backward to keep your center of gravity over your feet. Most fitness experts and strength coaches will agree that being able to perform at least 20-50 consecutive bodyweight squats with good form is a good basic standard to go by.";
String? Barbellbenchpress= "Grip a barbell with hands slightly wider than shoulder width. The bar should be directly over the shoulders. Press your feet firmly into the ground and keep your hips on the bench throughout the entire movement. Keep your core engaged and maintain a neutral spine position throughout the movement. For a 198-pound man — a very close match for the national average — who has no experience benching whatsoever, ExRx.net places the standard at 135 pounds. That jumps up to 175 for a novice and 215 for an intermediate lifter. At the advanced level, the number is 290 pounds.";
String? Sumodeadlift= "The Sumo deadlift is a variation of the conventional deadlift often adopted by powerlifters. The difference between the two lies in the setup of the lifter's feet and hands. When the bar is gripped with the lifter's hands inside their legs, the form is considered 'Sumo'.\n\nLike other deadlift variations, the sumo deadlift works the glutes, hamstrings, and back.\n\nThe main difference between the sumo and the conventional deadlift is the position of the feet and hands. Instead of being about hip-width apart, with sumo the feet are positioned wider than your hands. How wide apart they are depends on your height, but they will be much farther apart than shoulder width";
String? Yoga= "Yoga is essentially a spiritual discipline based on an extremely subtle science, which focuses on bringing harmony between mind and body. It is an art and scince of healthy living. The word 'Yoga' is derived from the Sanskrit root 'Yuj', meaning 'to join' or 'to yoke' or 'to unite'.\n\nYoga improves strength, balance and flexibility. Slow movements and deep breathing increase blood flow and warm up muscles, while holding a pose can build strength.";



// DIET DESCRIPTION -



String? Eggs = "egg, the content of the hard-shelled reproductive body produced by a bird, considered as food. While the primary role of the egg obviously is to reproduce the species, most eggs laid by domestic fowl, except those specifically set aside for hatching, are not fertilized but are sold mainly for human consumption. Eggs produced in quantity come from chickens, ducks, geese, turkeys, guinea fowl, pigeons, pheasants, and quail. This article describes the processing of chicken eggs, which represent the bulk of egg production in the United States and Europe. Duck eggs are consumed as food in parts of Europe and Asia, and goose eggs are also a food in many European countries. Commercial production of turkey and pigeon eggs is almost entirely confined to those used for producing turkey poults and young pigeons (squabs). Pheasant and quail eggs provide birds for hobby or sport use.";
String? Almonds= "Almonds are a nutritious tree nut rich in essential nutrients like fiber, vitamin E, manganese, and magnesium (7Trusted Source).\nThey’re also high in plant-based protein.\nEating almonds may benefit your health in several ways, including by lowering heart disease risk factors like high LDL (bad) cholesterol and high blood pressure (8Trusted Source, 9Trusted Source).\nTry adding some almonds to plant-based meals, like grain bowls and salads, for a boost of filling protein and fiber.\nIf you’re looking to add more nuts to your diet, also consider pistachios and cashews. Both of these healthy nuts are also packed with protein.";
String? Chickenbreast= "Chicken breast is an excellent choice if you’re trying to bump up your protein intake. In addition to protein, chicken provides a variety of B vitamins, plus minerals like zinc and selenium (10Trusted Source).\nChicken breast is also very versatile and easy to cook. It can taste delicious in a wide range of dishes.\nTry adding sliced chicken breast to salads, stir-fries, and soups to make these dishes more filling.";
String? Cottagecheese= "Cottage cheese is a type of cheese that is low in fat and calories, yet high in protein.\nIt’s rich in calcium, phosphorus, selenium, vitamin B12, riboflavin (vitamin B2), and various other nutrients (11Trusted Source).\nPlus, research suggests that cottage cheese is just as filling as eggs, making it an excellent choice for a satisfying meal or snack (12Trusted Source).\nFor example, you can pair it with cut-up fruit for a high protein breakfast on the go.";
String? Milk= "Dairy milk contains a little of nearly every nutrient that your body needs.\nIt’s a good source of high quality protein, and it’s high in vitamins and minerals, like calcium, phosphorus, and riboflavin (vitamin B2) (17Trusted Source).\nMany people with lactose intolerance can’t tolerate milk and other dairy products, and they avoid many dairy-containing foods (18Trusted Source).\nFortunately, there’s a variety of lactose-free products now on the market, including lactose-free milk, cheeses, and yogurts.\nNondairy milk alternatives, like cashew milk and coconut milk, can be a good substitute for milk in many cases, but they’re usually much lower in protein and don’t contain the same nutrients.\nIf you drink dairy milk, including lactose-free milk, it can be a good choice to increase your protein intake.";
String? Leanbeef= "Lean beef is a rich source of protein. It’s also high in bioavailable iron, zinc, selenium, and vitamins B12 and B6 (24Trusted Source).\nRed meat can be a part of a healthy diet, but it’s best to moderate your intake. Consuming high amounts of red meat has been linked to a higher risk of developing certain health conditions, including colorectal cancer (25Trusted Source).\nTry cutting back on red meat and eating plant-based protein, fish, and poultry more frequently.";
String? Fish= "Fish is an excellent source of protein and provides a number of important vitamins and minerals, like iodine, selenium, and vitamin B12 (26Trusted Source).\nPeople who include a lot of fish in their diet tend to have a lower risk of health conditions like heart disease and type 2 diabetes (27Trusted Source, 28Trusted Source).\nPlus, fatty fish like salmon and herring are high in omega-3 fats, which have powerful benefits for your overall health, including supporting heart health (29Trusted Source).";
String? Pumpkinseeds= "Pumpkin seeds are incredibly delicious and highly nutritious.\nFor example, they’re a great source of minerals like iron, phosphorus, magnesium, and zinc. Plus, they’re loaded with plant-based protein and fiber (37Trusted Source).\nTry adding pumpkin seeds to salads, baked goods, oatmeal, or yogurt, or mix them with unsweetened dried fruit and almonds for a convenient snack.";
String? Peanutandpeanutbutter= "Although people commonly think of peanuts as nuts, they’re actually legumes.\nPeanuts and peanut butter are packed with nutrients, like protein, folate, magnesium, and vitamin E (42Trusted Source).\nEating peanuts and peanut butter may help make you feel full due to their high protein content. In fact, studies show that adding peanut butter to a high carb meal may help reduce blood sugar spikes after the meal (43Trusted Source).\nFor example, putting peanut butter on a slice of bread can help you feel more satisfied and may help keep your blood sugar more stable after you eat.";
String? Oats= "Oats are an incredibly healthy whole grain and a great source of many vitamins, minerals, and antioxidants.\nRaw oats contain 70% carbs. A 1-cup (81-gram) serving contains 54 grams of carbs, including 8 grams of fiber. They are particularly high in a specific type of fiber called oat beta glucan (6Trusted Source, 7Trusted Source).\nOats are also a relatively good source of protein and contain more protein than most grains (8Trusted Source).\nResearch suggests that eating oats may reduce your risk of heart disease by lowering your cholesterol levels (9Trusted Source, 10Trusted Source, 11Trusted Source).\nEating oats may also lower blood sugar levels, especially in people with type 2 diabetes (12Trusted Source).";
String? Buckwheats= "Like quinoa, buckwheat is considered a pseudocereal. Despite its name, buckwheat is not related to wheat and does not contain gluten.\nRaw buckwheat contains 75 grams of carbs, while cooked buckwheat groats contain about 19.9 grams of carbs per 100-gram serving.\nBuckwheat is very nutritious, containing both protein and fiber. It also has more minerals and antioxidants than many other grains.\nAdditionally, studies in humans and animals suggest that it may be particularly beneficial for heart health and blood sugar regulation.";
String? Bananas= "Bananas are a popular fruit people love to use in many different recipes.\nOne large banana (136 grams) contains about 31 grams of carbs, either in the form of starches or sugars.\nBananas are also high in potassium and vitamins B6 and C, and they contain several beneficial plant compounds.\nThanks to their high content of potassium, bananas may help lower blood pressure and improve heart health.\nUnripe, green bananas are higher in starch. This transforms into natural sugars as the bananas ripen, turning yellow in the process. Thus, you’ll tend to get more starch and less sugar if you eat your bananas when they’re less ripe.\nUnripe and less ripe bananas also contain decent amounts of resistant starch and pectin, both of which support digestive health and provide fuel for the beneficial bacteria in your gut.";
String? Sweetpotatoes= "Sweet potatoes are a delicious, nutritious tuber or root vegetable.\nOne-half cup (100 grams) of mashed, cooked sweet potatoes with their skin on contains about 20.7 grams of carbs, which consists of starch, sugar, and fiber.\nSweet potatoes are also a rich source of vitamin A, vitamin C, and potassium.\nWhat’s more, they’re packed with antioxidants, which are compounds that help neutralize harmful free radicals in your cells to protect you against chronic disease.";
String? Beets= "Beets are a purple root vegetable that people sometimes refer to as beetroots.\nWhile they aren’t considered high in carbs overall, they do have a lot for a non-starchy vegetable. Raw and cooked beets contain about 10 grams of carbs per 100 grams, mainly from sugar and fiber.\nThey’re also packed with vitamins and minerals, along with powerful antioxidants and plant compounds.\nBeets are also high in inorganic nitrates, which are converted into nitric oxide in your body. Nitric oxide lowers blood pressure and may decrease the risk of several diseases.\nBeet juice is also very high in nitrates, and athletes sometimes use it to enhance their physical performance.\nThat’s because nitric oxide relaxes your blood vessels, allowing oxygen to flow more efficiently during exercise.";
String? Oranges= "Oranges are a popular type of citrus fruit.\nThey’re mainly composed of water and made up of about 15.5 grams of carbs per 100-gram serving. Oranges are also a good source of fiber.\nOranges are especially rich in vitamin C, potassium, and some B vitamins. In addition, they contain citric acid, as well as several potent plant compounds and antioxidants.\nEating oranges may improve heart health and help prevent kidney stones. They may also increase the absorption of iron from other foods you eat, which may help protect against iron deficiency anemia.";
String? Blueberries= "Blueberries are frequently marketed as a superfood due to their rich content of antioxidants.\nThey consist mostly of water, as well as about 14.5 grams of carbs per 100 grams.\nBlueberries also contain high amounts of many vitamins and minerals, including vitamin C, vitamin K, and manganese.\nStudies have shown that blueberries are a good source of antioxidant compounds, which can help protect your body against damaging free radicals. Studies suggest that eating blueberries may even improve memory in older adults.";
String? Apples= "Apples are well known for their sweet, tart flavor and crisp texture.\nThey’re available in many colors, sizes, and flavors, all of which generally contain about 14–16 grams of carbs per 100 grams.\nApples also boast many vitamins and minerals, but usually only in small amounts.\nApples may also offer several health benefits, including improved blood sugar management and heart health.\nEarly research suggests that adding apples to your diet may even be associated with a reduced risk of certain types of cancer. However, more research is needed.";
String? Kidneybeans= "Kidney beans are a member of the legume family and a variety of the common bean.\nCooked kidney beans contain about 21.5 grams of carbs per 100 grams, in the form of starches and fiber. This legume is also high in protein.\nKidney beans are a good source of many vitamins, minerals, and plant compounds. They’re also rich in antioxidant compounds, including anthocyanins and isoflavones.\nTheir numerous health benefits include improved blood sugar regulation and a reduced risk of colon cancer.\n";
String? Leafygreens= "Leafy greens contain virtually no fat and are loaded with beneficial minerals and vitamins, including calcium, potassium, folate and vitamins A and K.\nThey’re especially rich in certain plant compounds shown to reduce inflammation in your body.\nNot surprisingly, studies suggest that diets high in leafy greens may protect against certain conditions like heart disease, diabetes, and cancer,\nCommon leafy greens include:\n\nKaleSpinach\nArugula\nCollardgreens\nSwiss chard\nRomaine lettuce";
String? Fruits= "Fruits are an excellent option if you’re looking for a sweet, low-fat snack. Almost all fruits are low in fat and high in vitamins, minerals and fiber.\nThey’re also particularly rich in plant compounds. In fact, many of these beneficial plant compounds are responsible for fruits’ vibrant colors.\nIn addition, certain plant compounds are known to be potent antioxidants.\nFruits can be enjoyed fresh, dried or cooked. Try adding them to smoothies and salads or eating them with various dips.";
String? Beansandlegumes= "Legumes — also known as pulses — are a class of vegetable that includes beans, peas and lentils.\nThey’re low in fat and contain no cholesterol. What’s more, they’re high in fiber, protein, B vitamins and essential minerals, such as magnesium, zinc and iron.\nDue to their highly nutritious profile, beans and legumes offer several health benefits.\nAdditionally, regular consumption of beans and legumes may aid weight loss, as the high amounts of fiber can keep you feeling fuller longer.";
String? Tartcherryjuice= "Tart cherries, also known as sour or Montmorency cherries, are a fat-free fruit rich in anti-inflammatory compounds known as polyphenols.\nTart cherries may be beneficial for physically active individuals. Studies suggest that tart cherry juice reduces muscle inflammation and soreness after strenuous exercise.\nIt may also be beneficial for reducing symptoms of arthritis. In one study, drinking tart cherry juice daily decreased blood levels of inflammatory markers in women with osteoarthritis — the most common form of arthritis.";
String? Garlic= "Garlic’s bold flavor and aroma make it a popular ingredient. What’s more, it has very few calories and almost no fat.\nThroughout history, garlic has been used for medicinal purposes.\nResearch shows that garlic may enhance your immune system and help prevent the common cold when consumed regularly.\nSome studies also link the active compounds in garlic to reduced blood pressure and cholesterol, though high amounts of garlic or concentrated supplements are needed to have an effect.\n";
String? Mushrooms= "Mushrooms are a delicious, fat-free food with many purported health benefits.\nInterestingly, they don’t fall into any of the traditional food groups — they’re neither a fruit nor vegetable, grain or animal product.\nIn fact, mushrooms are fungi used widely as food and medicine for centuries.\nNutrients in mushrooms vary by type — but all contain potassium, fiber and various B vitamins and minerals. Certain types also pack a significant amount of vitamin D\nResearch suggests that mushrooms may strengthen your immune system and safeguard against certain cancers.";
String? Whiteleanfish= "White, lean fish includes haddock, cod, perch and pollock.\nThese types of fish are low in fat, contain very few calories and are an excellent source of high-quality protein.\nOne 3-ounce (85-gram) cooked serving of white fish contains around 1 gram of fat, 70–100 calories and a whopping 16–20 grams of protein.\nThese fish also provide several essential vitamins and minerals, including vitamin B12, phosphorus, selenium and niacin.\nDue to their mild flavors, white fish pair well with bold seasonings. They’re delicious in fish tacos or blackened, baked or broiled.";
String? Eggwhites= "While whole eggs are not considered a low-fat food, egg whites are.\nThat’s because the fat and cholesterol in eggs are concentrated in the yolks.\nIn fact, the white from one large egg contains 0 grams of fat, while a whole large egg including the yolk packs 5 grams of fat.\nEgg whites are also low in calories and a good source of high-quality protein, making them an ideal option to curb fat and calories from your diet.";
String? Homemadesmoothies= "Drinking homemade protein smoothies can be a highly nutritious and quick way to gain weight.\nMaking your own smoothies is the best way since commercial versions are often full of sugar and lack nutrients. It also gives you full control over the flavor and nutrient content.\n\nHere are just a few tasty variations you can try. You can combine each with 2 cups (470 mL) of dairy milk or soy milk if you have lactose intolerance. Both have more nutrients and calories than other alternative milks.\n\nChocolate banana nut shake: Combine 1 banana, 1 scoop of chocolate whey protein, and 1 tablespoon (15 mL) of peanut or another nut butter.\nVanilla berry shake: Combine 1 cup (237 mL) of fresh or frozen mixed berries, ice, 1 cup (237 mL) of high protein, full fat Greek yogurt, and 1 scoop of vanilla whey protein.";
String? Rice= "Rice is a convenient, low cost carb source to help you gain weight. Just 1 cup (158 grams) of cooked white rice provides 204 calories, 44 grams of carbs, and very little fat.\nRice is also fairly calorie-dense, meaning you can easily obtain a high amount of carbs and calories from a single serving. This helps you eat more food, especially if you have a poor appetite or get full quickly.\nWhen you’re on the go or in a rush, 2-minute packs of microwavable rice can be easily added to other protein sources and premade meals.\nAnother popular method is to prepare a large pot of rice, refrigerate it or freeze individual portions, and then combine it with different proteins and healthy fats for varied meals throughout the week.\nAnother way to boost taste and calories is to top your rice with a sauce like curry, pesto, or alfredo. You can buy these sauces ready-made if you’re pressed for time.";
String? Nutsandnutbutters= "Nuts and nut butters are perfect choices if you’re looking to gain weight.\nJust one small handful of raw almonds (1/4 cup) contains 170 calories, 6 grams of protein, 4 grams of fiber, and 15 grams of healthy fats\nSince nuts are very calorie-dense, just two handfuls per day with a meal or as a snack can quickly add hundreds of calories.\nYou can add nut butters to a variety of snacks or dishes, such as smoothies, yogurts, and crackers, to turn them into a high calorie snack in no time.\nFor a quick pick-me-up, try this peanut butter banana smoothie, with only three ingredients (270 calories, using whole milk). If you have a peanut allergy, substitute another nut butter.\nHowever, make sure you pick 100 percent nut butters with no added sugar or extra oils. Or better yet, make your own from this homemade almond butter recipe. It’s easy to make and easy on your wallet, too.";
String? Redmeats= "Red meats are probably one of the best muscle-building foods available.\nFor example, 6 ounces (170 grams) of steak contains around 5 grams of leucine.\nLeucine is the key amino acid your body needs to stimulate muscle protein synthesis and add new muscle tissue (8Trusted Source, 9). It also contains 456 calories and nearly 49 grams of protein.\nIn addition to this, red meats are one of the best natural sources of dietary creatine, which is possibly the world’s best muscle-building supplement (10).\nConsider choosing fattier cuts, which provide more calories than leaner meats, helping you take in extra calories and add weight.\nIn one study, 100 older women added 6 ounces (170 grams) of red meat to their diets and performed resistance training 6 days a week for 6 weeks.";
String? Potatoesandstarches= "Potatoes and other starchy foods are a very easy and cost-effective way to add in extra calories.\n\nTry to choose one of these healthy sources of starchy carbs:\n\nquinoaoats\ncorn\nbuckwheat\npotatoes and sweet potatoes\nsquash\nwinter root vegetables\nbeans and legumes";
String? Salmonandoilyfish= "Like red meat, salmon and oily fish are excellent sources of protein and important healthy fats.Out of all the nutrients that salmon and oily fish provide, omega-3 fatty acids are among the most significant and well known.They offer numerous benefits for your health and help fight diseases.Just one 6-ounce (170-gram) fillet of deboned wild sockeye salmon provides around 250 calories and 12 grams of healthy fats. The same serving packs 37 grams of high quality protein, helping you build muscle or gain weight.You can prepare salmon in a variety of ways: steamed, sautéed, smoked, grilled, baked, or poached. You can also try smoked salmon or even eat raw salmon in sushi and sashimi.";
String? Driedfruits= "Dried fruit is a high calorie snack that also provides antioxidants and micronutrients.You can get many different types of dried fruit, and they all have a naturally high sugar content. This makes them great for gaining weight, especially since they’re convenient to eat and taste great.While many people think fruits lose most of their nutrients when dried, this isn’t the case. Dried fruits contain lots of fiber and most of their vitamins and minerals remain intact.Try combining some dried fruit with a protein source, such as cuts of meat, cheese, or a whey protein shake. They also mix well with nuts and full fat plain Greek yogurt, providing a blend of healthy fats, protein, and other key nutrients.";
String? Wholegrainbread= "Whole grain breads are another good carb source to help you gain weight.You can make some very simple, high calorie, and well-balanced meals by combining bread with protein sources such as eggs, meat, and cheese.When purchasing bread, aim for natural whole grain and seeded breads. Healthier versions, such as Ezekiel bread, are available in most grocery stores.Sandwiches are one of the easiest, most versatile, and portable meals for helping you put on weight. Their ingredients are limited only by your imagination: meats, cheese, veggies, nut butter spreads, avocado, and more.";
String? Avacados= "Avocados are loaded with healthy fats.\nUnlike other whole fruits, avocados are fairly calorie-dense and therefore a great food to help you gain weight.\nAvocados are also high in vitamins, minerals, and various beneficial plant compounds.\nTry adding avocados to your main meals and other dishes such as omelets or sandwiches.\n\nOther delicious ways to enjoy the versatile avocado include:\n\nguacamolesalads\nsoupsn\nwraps\nsandwiches\nfries\nsushi";
String? Leanprotien= "Lean protein sources like chicken, turkey and grass-fed lean beef help keep you full, decrease cravings and stabilize blood sugar, says Feit. Plant-based proteins like legumes, beans and lentils have the same benefits, and they’re high in fiber as well, so they promote satiety.";
String? Vegetables= "Vegetables of all kinds can assist with weight loss, says Feit. For example, cruciferous vegetables like broccoli, cauliflower, Brussels sprouts and cabbage are high in fiber and vitamins and help reduce digestive issues. Meanwhile, dark green leafy vegetables contain protein and are a good source of vitamins, minerals and fiber. And crunchy vegetables like celery and jicama are great low-calorie options for snacking.";
String? Berries= "Berries are high in fiber, antioxidants and vitamin C—all things that your body needs to function optimally, says Feit.";
String? Nutsandseeds= "Nuts and seeds have different health benefits, says Feit. All nuts are a good source of fiber, protein and healthy fat, and they help decrease hunger. Meanwhile, seeds are a great source of minerals and healthy fat. Watch your portions here, too. One serving of nuts and seeds is equivalent to a quarter cup.";
String? Salmon= "Salmon is high in protein and omega-3 fatty acids, says Rima Kleiner, registered dietitian nutritionist and founder of wellness coaching company Smart Mouth Nutrition in Greensboro, North Carolina. Research suggests omega-3 fatty acids may help people with weight classified as overweight or obesity feel fuller[2]. And fish in general may help you feel satisfied and fuller longer than other proteins like eggs and beef, says Kleiner.";
String? Rawoats= "Raw oats are full of resistant starch—a type of starch that resists digestion—which is very weight loss-friendly, says Landau. In the process of digestion, resistant starch releases byproducts that can make your cells more responsive to insulin, helping to reduce stubborn fat around your midsection.";
String? Chiaseeds= "Chia seeds can help with weight control in two ways, says Dr. Olesiak. First, they’re loaded with fiber that can help you feel full, preventing overeating. Second, they expand in water, so if you eat them in their unsoaked form, they grow in your stomach, taking up more space and becoming a natural appetite suppressant.";
String? Water= "Water isn’t a food, but it’s just as important when it comes to healthy weight loss. “All of our body processes need water to function—metabolism is one of these processes,” says Feit, so be sure to stay well-hydrated.";
String? Paneer= "Paneer is an Indian cheese that’s made from curdled milk and some sort of fruit or vegetable acid like lemon juice. There are some distinct traits that make Paneer the cheese that it is:\nYou can eat paneer as a snack, with a meal, or even for breakfast. And while cheese might not seem like a common breakfast item, don’t knock it until you’ve tried it!\nThere are different theories as to where Paneer originated, the oldest and most common of them dating back to the 16th century in Southeast Asia where Persian and Afghani rulers first introduced the cheese. No matter its origin, it’s no secret that Paneer is a big and tasty part of the Indian culture.";

